
name: "Tag Image on Commit"
on: 
  push:


jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    -
      run: docker-compose up
      
   
 
   
