

name: "Tag Image on Commit"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
