
name: "Tag Image on Commit"
on: 
  push:


jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    -
      run: |
        docker build -t whist-app .
        docker tag whist-app:latest 930354804502.dkr.ecr.eu-west-2.amazonaws.com/whist-app:latest
        docker push 930354804502.dkr.ecr.eu-west-2.amazonaws.com/whist-app:latest
      
   
 
   
