
name: "Tag Image on Commit"
on: 
  push:


jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
          aws-region: us-west-2
          
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag image
      id:  build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: whist-app     
      run: |
        docker build -t whist-app .
        docker tag whist-app:latest 930354804502.dkr.ecr.eu-west-2.amazonaws.com/whist-app:latest
        docker push 930354804502.dkr.ecr.eu-west-2.amazonaws.com/whist-app:latest
      
   
 
   
